### ISSUE TITLE
Wrong additions and deletions counts

### ISSUE THREAD

**Issue by lhsazevedo** [php/web-doc#32]
## Description
The outdated files table is reporting wrong change counts. They seem to be broken after [9f67270](https://github.com/php/web-doc/commit/9f672701881bbbfb7838df13416ec5535174d08e).

It showing only the changes in the latest commit, while it should be comparing _each file_ against the commit specified by `EN-Revision` hash from it's translated counterpart.

## Example
In the image bellow `-2 +5` is reported, while the real counts should be `+92 -18` as seen on the [diff page](http://doc.php.net/revcheck.php?p=plain&lang=pt_br&hbp=41f1e8e0de702594b60d3aef233f3935929c22ef&f=reference/datetime/dateinterval/construct.xml&c=on).

![image](https://user-images.githubusercontent.com/7695608/150037719-0567a9f8-86c4-48bb-82f2-2b0c0900ad28.png)

## Fix
To get the real changes count, the command below should be used for each outdated file:
`git diff --numstat <en-revision-hash> -- <file-name>`

```
$ git diff --numstat 41f1e8e0de702594b60d3aef233f3935929c22ef -- reference/datetime/dateinterval/construct.xml
92      18      reference/datetime/dateinterval/construct.xml
```

I'm not aware of a way of obtaining the counts for all files in just shot, as the hashes differ from file to file.

**Comment by lhsazevedo** [comment]
I tried to simplify the main language loop in terms of readability and maintainability and came up with the result bellow. I find it easier understand and safer to modify. It is longer indeed, but maybe it's better to extract functions than to compress a lots of conditions in a few lines.

https://github.com/lhsazevedo/php-web-doc/blob/e2efd161435f0778d478ef51eaa7a94fe140146a/scripts/rev.php#L513-L571

Please tell me what you think.

**Comment by nilgun** [comment]
My goal was to reduce the generation time of the database. The change you
made was increasing the time to 80 seconds and git was crashing some files
(possibly due to migration to github). I tried to revert to the old value
(15 seconds) and get rid of the errors. Your new suggestion will increase
the time even more (2 git commands instead of 1 git command per file). For
now, returning to 80 seconds should suffice.

Lucas Henrique ***@***.***>, 19 Oca 2022 Çar, 08:29 tarihinde
şunu yazdı:

**Comment by lhsazevedo** [comment]
Got it. I'll try to reproduce and fix those git crashes locally.
Would you mind sharing scenarios/logs where they happen?

Note that the 80 seconds code already had two 2 git commands per file, a `git log` on line 257 that handles revcheck skips and a `git diff` on line 540 for change counts.

It's hard indeed to spot them inside the nested conditions:

```
foreach( $LANGS as $lang )
{
    if ( )
    {
        ...
    } else {
        if ( ){
            ...
        } elseif ( ) {
            ...
->          $subject = `git diff --numstat $trFile->hash -- {$filename}`;
            ...
        }
        if ( )
            ...
        if ( ) {
            ...
->          $hashes = explode ("\n" , `git log -2 --format=%H -- {$filename}`);
            ...
            if ( )
                ...
        }
        ...
    }
}
```
