### ISSUE TITLE
Missed documentation pages

### ISSUE THREAD

**Issue by PSF1** [php/web-doc#47]
Hello,

While I was browsing the documentation at "https://www.php.net/manual/es/datetime.formats.relative.php", I attempted to switch to the English version (as well as other languages) but noticed that those pages do not exist. For instance:

- https://www.php.net/manual/en/datetime.formats.relative.php
- https://www.php.net/manual/de/datetime.formats.relative.php
- https://www.php.net/manual/fr/datetime.formats.relative.php
- ...

All of these links return a 404 error. It appears that the translations or alternative language versions of this page are missing. Could this be looked into?

Thank you.

**Comment by Girgias** [comment]
The spanish translation of the documentation is extremely outdated, see the status: http://doc.php.net/revcheck.php?p=filesummary&lang=es

So the problem is that the Spanish version has a page that no longer exists in English, which is the canonical version of the documentation.

If you want to help translating/updating the Spanish docs let me know and I'll onboard you.

**Comment by PSF1** [comment]
Thank you for your rapid response and the insight into the issue with the Spanish documentation. I am eager to contribute to updating it; however, my current time availability is quite limited.

Could you outline the process and commitment required for contributing? I aim to understand how I might help within my constraints before committing to a workload I might not be able to manage.

Thanks for considering my situation, and I look forward to finding a way to contribute effectively.

**Comment by Girgias** [comment]
Any help would do!

You can clone https://github.com/php/doc-es, choose one file from http://doc.php.net/revcheck.php?p=filesummary&lang=es, check the diff, update it (and update the EN-Revision tag comment) and open a PR.

Feel free to ping me when you open a PR!

The priority would be files in the `/language/` folder.
