### ISSUE TITLE
pt_BR translation data missing from web-doc pages

### ISSUE THREAD

**Issue by leonardolara** [php/web-doc#59]
pt_BR translation data is missing from web-doc pages after commit [4e57bbb](https://github.com/php/web-doc/commit/4e57bbbc6ed10617cdf82ad3de08a31e759b322c)

It could be just a case sensitivity issue.

**Comment by jimwins** [comment]
Sorry about that, all fixed up now.

**Comment by alfsb** [comment]
Thanks for the fix! This status page (and diff links) are very helpful.

**Comment by Girgias** [comment]
I am going to close this as it seems this has been fixed.
